// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/analyze.tsx";
import * as $1 from "./routes/api/analyze.tsx";
import * as $2 from "./routes/api/upload.tsx";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/upload.tsx";
import * as $$0 from "./islands/Analyze.tsx";
import * as $$1 from "./islands/Header.tsx";
import * as $$2 from "./islands/Homepage.tsx";
import * as $$3 from "./islands/Rating.tsx";
import * as $$4 from "./islands/Upload.tsx";

const manifest = {
  routes: {
    "./routes/analyze.tsx": $0,
    "./routes/api/analyze.tsx": $1,
    "./routes/api/upload.tsx": $2,
    "./routes/index.tsx": $3,
    "./routes/upload.tsx": $4,
  },
  islands: {
    "./islands/Analyze.tsx": $$0,
    "./islands/Header.tsx": $$1,
    "./islands/Homepage.tsx": $$2,
    "./islands/Rating.tsx": $$3,
    "./islands/Upload.tsx": $$4,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
